version: "3.6"
services:
  ae-monitor:
    build: .
    container_name: ae-monitor
    depends_on:
      - monitor-postgres
    environment:
      - NODE_URL=https://mainnet.aeternity.io
      - NODE_ENV=production
      # all optional
      - POSTGRES_PASSWORD=postgres # replace with your own credentials
      - POSTGRES_USER=postgres # replace with your own credentials
      - POSTGRES_DB=mainnet
      - POSTGRES_HOST=monitor-postgres
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: mgrafana
    restart: unless-stopped
    links:
      - monitor-postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=test # add your own credentials here
      - GF_USERS_ALLOW_SIGN_UP=false

  monitor-postgres:
    image: postgres:12
    hostname: monitor-postgres
    restart: unless-stopped
    container_name: monitor-postgres
    environment:
      - POSTGRES_PASSWORD=postgres # replace with your own credentials
      - POSTGRES_USER=postgres # replace with your own credentials
      - POSTGRES_DB=mainnet
